### ISSUE TITLE
Fraction Support (1/7, 1/9 and 1/10)

### ISSUE THREAD

**Issue by JamoCA** [gcardone/junidecode#10]
I noticed that most of the unicode fractions are supported:
http://unicodefractions.com/

...but it appears that the following fractions aren't converted.
    1/7 = ⅐ 
    1/9 = ⅑
    1/10 = ⅒

The library outputs "[?]" instead of the expected fraction.

NOTE: ICU4J Transliteration passes these through unchanged versus converting them.

**Comment by gcardone** [comment]
Reasonable. I'll get to it later this week (hopefully).
