### ISSUE TITLE
Ý->U instead of Y

### ISSUE THREAD

**Issue by romanchyla** [gcardone/junidecode#12]
thanks for the library! i think i have found a small issue with the mapping; when using python unidecode library (0.04.21)

```áéíóůýÁÉÍÓŮÝ -> aeiouyAEIOUY```

with latest junicode release, the output is slightly different: 

`áéíóůýÁÉÍÓŮÝ->aeiouyAEIOUU`

**Comment by romanchyla** [comment]
unless the packaged jar has different code, it shouldn't be happening:

https://github.com/gcardone/junidecode/blob/master/src/main/java/net/gcardone/junidecode/X00.java#L247

so i'm bit stumped; i can try to build the library (next week however)

**Comment by gcardone** [comment]
I've been a bad maintainer and the current jar is v0.4. I need to release a new jar synced at 45aabffe51c247fe41d0a12a49ab9c269bc89771 or later (which includes a fix for the issue you're seeing). Building your own jar should fix the problem.

**Comment by romanchyla** [comment]
Thanks!
