### ISSUE TITLE
Strange behavior while decoding...

### ISSUE THREAD

**Issue by DanyKreyo** [gcardone/junidecode#17]
Hi,
I'm not familiar with cyrillique practices but when I encode Головина the result is Golovina, but when I encode головина (first letter in lower case) I obtain gholovina (with an additional "h")
Is it the normal behavior ? If not is it planed to be resolved soon ?
it is not the only case where "g" is turned to "gh" when changed to lower case
Many thanks for your help

Regards

**Comment by gcardone** [comment]
Г should be U+0490, and г U+0433. Encoding of Cyrillic letters is in [X04.java](https://github.com/gcardone/junidecode/blob/master/src/main/java/net/gcardone/junidecode/X04.java), so these should be decoded as `G'` and `g` respectively. These mapping come from [Unidecode's x04.pm](https://metacpan.org/source/SBURKE/Text-Unidecode-1.30/lib%2FText%2FUnidecode%2Fx04.pm), and as such the transliteration is working as intended.

I did not decide those mappings, I merely ported them from Unidecode. So this is Working as Intended.
