### ISSUE TITLE
JDK 11 Compatibility

### ISSUE THREAD

**Issue by AndreyBozhko** [gcardone/junidecode#20]
Hi @gcardone, thanks for releasing the version 0.5.1 of the library!

It seems that the latest artifact in sonatype is only compatible with JDK 17 or later. Would it be possible to lower the JDK target compatibility to 11?

**Comment by zanonmark** [comment]
+1 for me.

Thanks,
MZ

**Comment by gcardone** [comment]
Needs a new upload to Sonatype to be fixed.

**Comment by gcardone** [comment]
The new version is on sonatype and on the central repository.
