### ISSUE TITLE
Empty decode with arabic characters

### ISSUE THREAD

**Issue by silvioOlivastri** [gcardone/junidecode#5]
Hi,

I try to decode this string:
```
ﺑﺮﺗﺎﺡ ﻭﺑﻄﻤﻦ ﻭﺍﻧﺎ ﻓﻲ ﺣﻀﻨﻚ ﺍﺧﺎﻑ ﻣﻦ ﺍﻳﻪ
ﻟﻘﻴﺖ ﻓﻴﻚ ﺍﻟﻠﻲ ﻛﺎﻥ ﻧﻔﺴﻲ ﺣﺒﻴﺒﻲ ﻓﻲ ﻟﻴﻠﺔ ﺍﻧﻲ ﺍﻻﻗﻴﺔ
ﻭﻧﺴﻴﺖ ﺣﻴﺎﺗﻲ ﻭﺩﻧﻴﺘﻲ ﻗﺒﻠﻚ ﻣﺒﺤﺴﺒﻬﺎﺵ ﻋﺸﺎﻥ ﺍﻟﺪﻧﻴﺎ ﻣﻦ
ﻏﻴﺮﻙ ﺣﻘﻴﻘﻲ ﺣﺒﻴﺒﻲ ﻭﻻ ﺗﺘﻌﺎﺵ
ﻭﻳﺎﻙ ﺍﻧﺎ ﻟﻘﻴﺖ ﻟﻠﺪﻧﻴﺎ ﻣﻌﻨﻲ ﺟﺪﻳﺪ
ﻭﺣﺒﻚ ﻛﻞ ﻟﻴﻠﺔ ﻳﺰﻳﺪ ﻭﺟﻨﺒﻚ ﻛﻞ ﻳﻮﻡ ﻳﻮﻡ ﻋﻴﺪ
ﻭﻳﺎﻙ ﺑﺘﺘﻀﺤﻜﻠﻲ ﺍﻟﺤﻴﺎﺓ ﻭﻳﺎﻙ ﺻﺎﺣﻠﺔ ﺍﻟﺪﻧﻴﺎ ﺑﻴﻚ
ﻭﻣﻌﺎﻙ ﻭﻣﻦ ﻗﻠﺒﻲ ﺑﻘﻮﻝ ﺑﻬﻮﺍﻙ
```

but the result of
```java
String s = "ﺑﺮﺗﺎﺡ ﻭﺑﻄﻤﻦ ﻭﺍﻧﺎ ﻓﻲ ﺣﻀﻨﻚ ﺍﺧﺎﻑ ﻣﻦ ﺍﻳﻪ\n" +
                "ﻟﻘﻴﺖ ﻓﻴﻚ ﺍﻟﻠﻲ ﻛﺎﻥ ﻧﻔﺴﻲ ﺣﺒﻴﺒﻲ ﻓﻲ ﻟﻴﻠﺔ ﺍﻧﻲ ﺍﻻﻗﻴﺔ\n" +
                "ﻭﻧﺴﻴﺖ ﺣﻴﺎﺗﻲ ﻭﺩﻧﻴﺘﻲ ﻗﺒﻠﻚ ﻣﺒﺤﺴﺒﻬﺎﺵ ﻋﺸﺎﻥ ﺍﻟﺪﻧﻴﺎ ﻣﻦ\n" +
                "ﻏﻴﺮﻙ ﺣﻘﻴﻘﻲ ﺣﺒﻴﺒﻲ ﻭﻻ ﺗﺘﻌﺎﺵ\n" +
                "ﻭﻳﺎﻙ ﺍﻧﺎ ﻟﻘﻴﺖ ﻟﻠﺪﻧﻴﺎ ﻣﻌﻨﻲ ﺟﺪﻳﺪ\n" +
                "ﻭﺣﺒﻚ ﻛﻞ ﻟﻴﻠﺔ ﻳﺰﻳﺪ ﻭﺟﻨﺒﻚ ﻛﻞ ﻳﻮﻡ ﻳﻮﻡ ﻋﻴﺪ\n" +
                "ﻭﻳﺎﻙ ﺑﺘﺘﻀﺤﻜﻠﻲ ﺍﻟﺤﻴﺎﺓ ﻭﻳﺎﻙ ﺻﺎﺣﻠﺔ ﺍﻟﺪﻧﻴﺎ ﺑﻴﻚ\n" +
                "ﻭﻣﻌﺎﻙ ﻭﻣﻦ ﻗﻠﺒﻲ ﺑﻘﻮﻝ ﺑﻬﻮﺍﻙ";

System.out.println("Decode: "+ Junidecode.unidecode(s));
```

is: 
```
Decode:        
         
       
    
     
        
      
    
```

can you fix this bug?

**Comment by gcardone** [comment]
Arabic blocks (0600–06FF, 0750–077F, 08A0–08FF) are pretty much unsupported by junidecode. The article by[ Sean M. Burke on Text::Unidecode](http://interglacial.com/%7Esburke/tpj/as_html/tpj22.html) explains why:

> My Library of Congress ALA-LC Romanization Tables reference for Arabic goes on for pages and pages. It notes, for example, that one character (Unicode 0x0629, called "teh marbuta", which looks oddly like a "ö") is to be transliterated as "h" when it's on nouns that are indefinite or preceded by a definite article, or as "t" when it is on construct state nouns, or as "tan" when it's an adverb suffix. I have not the faintest idea what the "construct state" is or how to identify it, or how to tell an indefinite noun or an adverb from any other kind of word in Arabic. I am rather sure, however, that it cannot be done with a mere regular expression, and that is not something I say lightly! 

Please refer to the article for more details, because junidecode is just a port to Java of Text::Unidecode.

Not mapping arabic characters is working as intended.
