### ISSUE TITLE
Issue with "и" & "Я" decoding

### ISSUE THREAD

**Issue by tset2411** [gcardone/junidecode#6]
Hi,

I tried this library for below String
`é, é, ō, øe, ø, Æ, Œ, Å, и, Я , Tĥïŝ ĩš â fůňķŷ Šťŕĭńġ, Ȳ  Ѷ  Ǭ  Ƈ `
I got the below result
`e, e, o, oe, o, AE, OE, A, i, Ia , This is a funky String, Y  Y  O  C`

As you can see for 'и' i got 'i', it should be 'N' and for 'Я' i got 'la', it should be 'R'

Code is as below
```
public static void main(String args[]) {
   String str3 = "é, é, ō, øe, ø, Æ, Œ, Å, и, Я , Tĥïŝ ĩš â fůňķŷ Šťŕĭńġ, Ȳ  Ѷ  Ǭ  Ƈ";
   System.out.println(Junidecode.unidecode(str3));
}

```
Do i need to make any specific configuration?
Please guide 

Thanks

**Comment by gcardone** [comment]
_[и](https://en.wikipedia.org/wiki/I_(Cyrillic))_ is a cyrillic letter that commonly represents the vowel /i/. Its shape is derived from the capital Greek letter Eta ⟨Η⟩. It can not be mapped to "n", despite the somewhat similar shape.

In a similar vein, _[Я](https://en.wikipedia.org/wiki/Ya_(Cyrillic))_ (Ya) is a  vowel and typically sounds as /ja/, and it's not related to "R".

If you want to apply special mappings, you will have to do so yourself before using junidecode.

**Comment by tset2411** [comment]
@gcardone Yes i got it. Thanks.
